# Generated by Django 3.2.25 on 2024-06-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cartitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartitem',
        ),
    ]
