# Generated by Django 3.2.25 on 2024-06-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
