# Generated by Django 3.2.25 on 2024-06-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
