# Generated by Django 3.2.25 on 2024-07-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
