# Generated by Django 3.2.25 on 2024-07-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productname',
            new_name='products',
        ),
    ]
