# Generated by Django 3.2.25 on 2024-07-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
